
import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  ar: {
    title: "سمارت سايت - ملتقى الأفكار",
    heading: "حوّل فكرتك إلى واقع ذكي",
    labelSite: "اسم المشروع",
    labelEmail: "بريدك الإلكتروني",
    labelIdea: "اشرح فكرتك بالتفصيل",
    submitBtn: "إرسال الفكرة للمراجعة",
    discussBtn: "ناقش الفكرة مع المساعد",
    adminLink: "لوحة التحكم",
    homeLink: "الرئيسية",
    successMsg: "تم استلام فكرتك! فريقنا والذكاء الاصطناعي سيعملان عليها الآن.",
    loading: "جاري تحليل البيانات...",
    chatPlaceholder: "تحدث معي عن تفاصيل فكرتك...",
    codeHeading: "النموذج الأولي للكود",
    evalHeading: "تقرير التحليل الذكي",
    tableSite: "المشروع",
    tableEmail: "صاحب الفكرة",
    tableIdea: "الوصف",
    tableEval: "التقييم",
    tableStatus: "الحالة",
    tableDate: "التاريخ"
  },
  en: {
    title: "SmartSite - Idea Hub",
    heading: "Turn Your Vision Into Smart Code",
    labelSite: "Project Name",
    labelEmail: "Your Email Address",
    labelIdea: "Explain your idea in detail",
    submitBtn: "Submit Idea for Review",
    discussBtn: "Discuss with AI Assistant",
    adminLink: "Dashboard",
    homeLink: "Home",
    successMsg: "Idea received! Our AI is working on it right now.",
    loading: "Analyzing data...",
    chatPlaceholder: "Tell me more about your project...",
    codeHeading: "Initial Prototype Code",
    evalHeading: "Smart Analysis Report",
    tableSite: "Project",
    tableEmail: "Founder",
    tableIdea: "Description",
    tableEval: "Evaluation",
    tableStatus: "Status",
    tableDate: "Date"
  },
  fr: {
    title: "SmartSite - Hub d'Idées",
    heading: "Transformez votre vision en code intelligent",
    labelSite: "Nom du Projet",
    labelEmail: "Votre Adresse Email",
    labelIdea: "Expliquez votre idée en détail",
    submitBtn: "Soumettre l'idée",
    discussBtn: "Discuter avec l'IA",
    adminLink: "Tableau de Bord",
    homeLink: "Accueil",
    successMsg: "Idée reçue ! Notre IA y travaille en ce moment.",
    loading: "Analyse en cours...",
    chatPlaceholder: "Parlez-moi de votre projet...",
    codeHeading: "Prototype de Code Initial",
    evalHeading: "Rapport d'Analyse Intelligente",
    tableSite: "Projet",
    tableEmail: "Fondateur",
    tableIdea: "Description",
    tableEval: "Évaluation",
    tableStatus: "Statut",
    tableDate: "Date"
  },
  es: {
    title: "SmartSite - Hub de Ideas",
    heading: "Transforma tu visión en código inteligente",
    labelSite: "Nombre del Proyecto",
    labelEmail: "Tu Correo Electrónico",
    labelIdea: "Explica tu idea en detalle",
    submitBtn: "Enviar Idea",
    discussBtn: "Hablar con el Asistente IA",
    adminLink: "Panel de Control",
    homeLink: "Inicio",
    successMsg: "¡Idea recibida! Nuestra IA está trabajando en ello.",
    loading: "Analizando datos...",
    chatPlaceholder: "Cuéntame más sobre tu proyecto...",
    codeHeading: "Prototipo de Código Inicial",
    evalHeading: "Informe de Análisis Inteligente",
    tableSite: "Proyecto",
    tableEmail: "Fundador",
    tableIdea: "Descripción",
    tableEval: "Evaluación",
    tableStatus: "Estado",
    tableDate: "Fecha"
  }
};
